ALTER TABLE artists
    ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;

ALTER TABLE artists
    ADD COLUMN rating INTEGER CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE albums
    ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;

ALTER TABLE albums
    ADD COLUMN rating INTEGER CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE songs
    ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;

ALTER TABLE songs
    ADD COLUMN rating INTEGER CHECK (rating BETWEEN 1 AND 5);
